
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RANURA
 */
public class penjualantiketbioskop extends javax.swing.JFrame {
     int  reguler,vip,vvip,harga,beli,total,bayar,kembali;
    /**
     * Creates new form penjualantiketbioskop
     */
    public penjualantiketbioskop() {
    initComponents();

    // Inisialisasi array pilihan studio
    String[] listStudio = {"Pilih Studio ","Studio 1", "Studio 2", "Studio 3", "Studio 4","Studio 5"};

    // Membuat model ComboBox untuk pilihan studio
    javax.swing.DefaultComboBoxModel<String> pilihStudio = new javax.swing.DefaultComboBoxModel<>(listStudio);

    // Menetapkan model ComboBox pilihan studio ke komponen ComboBox
    cb_studio.setModel(pilihStudio);

    // Inisialisasi array pilihan film
    String[] listFilm = {"Pilih Film","Siksa Neraka", "Ayat Ayat Cinta", "Penggonan Wingit", "172 Days", "Insidious: The Red Door", "Ant Man", "Pengabdi Setan", "Air Mata Di Ujung Sejadah", "Evil Dead Rise"};

    // Membuat model ComboBox untuk pilihan film
    javax.swing.DefaultComboBoxModel<String> pilihFilm = new javax.swing.DefaultComboBoxModel<>(listFilm);

    // Menetapkan model ComboBox pilihan film ke komponen ComboBox
    cb_film.setModel(pilihFilm);
}

    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cb_kursi = new javax.swing.JComboBox<>();
        rb_reguler = new javax.swing.JRadioButton();
        rb_vip = new javax.swing.JRadioButton();
        rb_vvip = new javax.swing.JRadioButton();
        txt_harga = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        txt_jumlahbeli = new javax.swing.JTextField();
        txt_pembayaran = new javax.swing.JTextField();
        txt_kembalian = new javax.swing.JTextField();
        txt_totalbayar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        btn_cetaklaporan = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        btn_proses = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        cb_film = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cb_studio = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        gendre = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 6));
        jPanel1.setForeground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel1.setText("PEMESANAN TIKET BIOSKOP CINEMA 23");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Kursi           :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Pilihan Tiket  :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Harga          :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        cb_kursi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kursi", "A", "B", "C", "D", "E" }));
        cb_kursi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_kursiActionPerformed(evt);
            }
        });
        jPanel1.add(cb_kursi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 110, -1));

        buttonGroup1.add(rb_reguler);
        rb_reguler.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rb_reguler.setText("Reguler");
        rb_reguler.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rb_regulerStateChanged(evt);
            }
        });
        rb_reguler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_regulerActionPerformed(evt);
            }
        });
        jPanel1.add(rb_reguler, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        buttonGroup1.add(rb_vip);
        rb_vip.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rb_vip.setText("VIP");
        rb_vip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_vipActionPerformed(evt);
            }
        });
        jPanel1.add(rb_vip, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        buttonGroup1.add(rb_vvip);
        rb_vvip.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rb_vvip.setText("VVIP");
        rb_vvip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_vvipActionPerformed(evt);
            }
        });
        jPanel1.add(rb_vvip, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        txt_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hargaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 150, -1));

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Jumlah Yang Dipesan  :");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Nama Pemesan            :");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Total Bayar                  :");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Pembayaran                 :");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Kembalian                   :");

        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });

        txt_jumlahbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jumlahbeliActionPerformed(evt);
            }
        });
        txt_jumlahbeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_jumlahbeliKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_jumlahbeliKeyTyped(evt);
            }
        });

        txt_pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pembayaranActionPerformed(evt);
            }
        });
        txt_pembayaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_pembayaranKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_pembayaranKeyTyped(evt);
            }
        });

        txt_kembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kembalianActionPerformed(evt);
            }
        });

        txt_totalbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalbayarActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(204, 255, 255));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("ID Pemesan                 :");

        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        txt_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_idKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_jumlahbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txt_totalbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addGap(33, 33, 33)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_jumlahbeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_totalbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 410, 310));

        btn_cetaklaporan.setBackground(new java.awt.Color(236, 255, 0));
        btn_cetaklaporan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_cetaklaporan.setText("Cetak Laporan");
        btn_cetaklaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetaklaporanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cetaklaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 490, -1, -1));

        btn_keluar.setBackground(new java.awt.Color(250, 11, 11));
        btn_keluar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 540, 130, 40));

        btn_proses.setBackground(new java.awt.Color(27, 241, 82));
        btn_proses.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_proses.setText("Pesan Kembali");
        btn_proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prosesActionPerformed(evt);
            }
        });
        jPanel1.add(btn_proses, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 490, -1, -1));

        txt_area.setColumns(20);
        txt_area.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        txt_area.setRows(5);
        jScrollPane1.setViewportView(txt_area);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 520, 290));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Judul Film    :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        cb_film.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_filmActionPerformed(evt);
            }
        });
        jPanel1.add(cb_film, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Studio         :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        cb_studio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_studioActionPerformed(evt);
            }
        });
        jPanel1.add(cb_studio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 110, -1));

        jPanel3.setBackground(new java.awt.Color(255, 102, 0));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 50));

        gendre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gendreActionPerformed(evt);
            }
        });
        jPanel1.add(gendre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 210, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Genre               :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_kursiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_kursiActionPerformed
        // TODO add your handling code here:
        // deklarasi untuk menentukan harga setiap kursi yang dibeli
        if(cb_kursi.getSelectedItem().equals("Pilih Kursi"))
        {
        buttonGroup1.clearSelection();
        txt_harga.setText("");
        }
        else if(cb_kursi.getSelectedItem().equals("A"))
        {
         reguler=100000;
         vip=150000;
         vvip=200000;
        }
        else if(cb_kursi.getSelectedItem().equals("B"))
        {
         reguler=120000;
         vip=155000;
         vvip=250000;
        }
        else if(cb_kursi.getSelectedItem().equals("C"))
        {
         reguler=130000;
         vip=170000;
         vvip=270000;
        }
        else if(cb_kursi.getSelectedItem().equals("D"))
        {
         reguler=140000;
         vip=180000;
         vvip=300000;
        }
        else if(cb_kursi.getSelectedItem().equals("E"))
        {
         reguler=150000;
         vip=200000;
         vvip=320000;
        }
    }//GEN-LAST:event_cb_kursiActionPerformed

    private void rb_vvipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_vvipActionPerformed
        // TODO add your handling code here:
         //menampilkan harga setelah pilih tiket
        //vvip
        if(rb_vvip.isSelected())
        {
        txt_harga.setText(String.valueOf(vvip));
        }
    }//GEN-LAST:event_rb_vvipActionPerformed

    private void txt_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargaActionPerformed

    private void rb_regulerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rb_regulerStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_regulerStateChanged

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void txt_jumlahbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jumlahbeliActionPerformed
        // TODO add your handling code here:
        //input jumlah tiket dan total pembayaran
        beli=Integer.parseInt(txt_jumlahbeli.getText());
        harga=Integer.parseInt(txt_harga.getText());
        total=bayar*harga;
        txt_totalbayar.setText(String.valueOf(total));
    }//GEN-LAST:event_txt_jumlahbeliActionPerformed

    private void txt_totalbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalbayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalbayarActionPerformed

    private void txt_pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pembayaranActionPerformed
        // TODO add your handling code here:
        bayar=Integer.parseInt(txt_pembayaran.getText());
        kembali=Integer.parseInt(txt_totalbayar.getText());
        total=bayar-kembali;
        txt_kembalian.setText(String.valueOf(total));
    }//GEN-LAST:event_txt_pembayaranActionPerformed

    private void txt_kembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kembalianActionPerformed

    private void btn_cetaklaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetaklaporanActionPerformed
        // TODO add your handling code here:
        int numberOfCopies = 1; //  nilai ini sesuai dengan jumlah salinan yang diinginkan
    int currentCopy = 0;
    do {
        txt_area.append(
        "ID Pemesan              :"+txt_id.getText()+"\n"+   
        "Studio                       :"+cb_studio.getSelectedItem()+"\n"+
        "Kode kursi                :"+cb_kursi.getSelectedItem()+"\n"+       
        "Nama Pemesan       :"+txt_nama.getText()+"\n"+
        "Judul Film                :"+cb_film.getSelectedItem()+"\n"+
        "Genre                       :"+gendre.getText()+"\n"+
        "Jumlah Pesanan      :"+txt_jumlahbeli.getText()+"\n"+
        "Total Pembayaran  :Rp."+txt_totalbayar.getText()+"\n"+
        "Pembayaran            :Rp."+txt_pembayaran.getText()+"\n"+
        "Kembalian               :Rp."+txt_kembalian.getText()+"\n"+
        "Terima Kasih " +txt_nama.getText()+ " Sudah Memesan\n ");
        currentCopy++;
    } while (currentCopy < numberOfCopies);
    
    
    }//GEN-LAST:event_btn_cetaklaporanActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        int answer=JOptionPane.showConfirmDialog(null,"Apakah anda yakin Ingin keluar?","Keluar",JOptionPane.OK_OPTION);
        if(answer==JOptionPane.OK_OPTION)
        {
         new login1().show();
          this.dispose();
       
        }
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void btn_prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prosesActionPerformed
        // TODO add your handling code here:
        buttonGroup1.clearSelection();
        txt_harga.setText("");
        cb_kursi.setSelectedItem("");
        cb_film.setSelectedItem("");
        cb_studio.setSelectedItem("");
        txt_id.setText("");
        txt_nama.setText("");
        txt_totalbayar.setText("");
        txt_jumlahbeli.setText("");
        txt_pembayaran.setText("");
        txt_kembalian.setText("");
    }//GEN-LAST:event_btn_prosesActionPerformed

    private void rb_regulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_regulerActionPerformed
        // TODO add your handling code here:
        //menampilkan harga setelah pilih tiket
        //reguler
        if(rb_reguler.isSelected())
        {
        txt_harga.setText(String.valueOf(reguler));
        }
    }//GEN-LAST:event_rb_regulerActionPerformed

    private void rb_vipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_vipActionPerformed
        // TODO add your handling code here:
         //menampilkan harga setelah pilih tiket
        //vip
        if(rb_vip.isSelected())
        {
        txt_harga.setText(String.valueOf(vip));
        }
    }//GEN-LAST:event_rb_vipActionPerformed

    private void txt_jumlahbeliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jumlahbeliKeyReleased
        // TODO add your handling code here:
        int a,b,c;
        a=Integer.valueOf(txt_harga.getText());
        b=Integer.valueOf(txt_jumlahbeli.getText());
        c=a*b;
        txt_totalbayar.setText(""+c);
    }//GEN-LAST:event_txt_jumlahbeliKeyReleased

    private void txt_pembayaranKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pembayaranKeyReleased
        // TODO add your handling code here:
         int a,b,c;
        a=Integer.valueOf(txt_pembayaran.getText());
        b=Integer.valueOf(txt_totalbayar.getText());
        c=a-b;
        txt_kembalian.setText(""+c);
    }//GEN-LAST:event_txt_pembayaranKeyReleased

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idKeyTyped
        // TODO add your handling code here:
        char enter=evt.getKeyChar();
        if(!(Character.isDigit(enter)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txt_idKeyTyped

    private void txt_jumlahbeliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jumlahbeliKeyTyped
        // TODO add your handling code here:
         char enter=evt.getKeyChar();
        if(!(Character.isDigit(enter)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txt_jumlahbeliKeyTyped

    private void txt_pembayaranKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pembayaranKeyTyped
        // TODO add your handling code here:
        char enter=evt.getKeyChar();
        if(!(Character.isDigit(enter)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txt_pembayaranKeyTyped

    private void cb_filmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_filmActionPerformed
        // TODO add your handling code here:
         if(cb_film.getSelectedItem().equals("Pilih Film"))
        {
        buttonGroup1.clearSelection();
        }
        else if(cb_film.getSelectedItem().equals(""))
        {
            
        }
         switch(cb_film.getSelectedIndex()){
            case 0:
                gendre.setText("");
                break;
            case 1:
                gendre.setText("Horor");
                break;
            case 2:
                gendre.setText("Romantis");
                break;    
            case 3:
                gendre.setText("Horor");
                break;
            case 4:
                gendre.setText("Romantis");
                break;
            case 5:
                gendre.setText("Horor");
                break;
            case 6:
                gendre.setText("Action");
                break;  
            case 7:
                gendre.setText("Horor");
                break;  
            case 8:
                gendre.setText("Drama");
                break;   
             case 9:
                gendre.setText("Horor");
                break;       
        }
        
    }//GEN-LAST:event_cb_filmActionPerformed

    private void cb_studioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_studioActionPerformed
    
        // TODO add your handling code here:
         if(cb_film.getSelectedItem().equals("Pilih Film"))
        {
        buttonGroup1.clearSelection();
        }
        else if(cb_film.getSelectedItem().equals(""))
        {
            
        }
    }//GEN-LAST:event_cb_studioActionPerformed

    private void gendreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gendreActionPerformed
        
        
    }//GEN-LAST:event_gendreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(penjualantiketbioskop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(penjualantiketbioskop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(penjualantiketbioskop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(penjualantiketbioskop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new penjualantiketbioskop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cetaklaporan;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_proses;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_film;
    private javax.swing.JComboBox<String> cb_kursi;
    private javax.swing.JComboBox<String> cb_studio;
    private javax.swing.JTextField gendre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb_reguler;
    private javax.swing.JRadioButton rb_vip;
    private javax.swing.JRadioButton rb_vvip;
    private javax.swing.JTextArea txt_area;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_jumlahbeli;
    private javax.swing.JTextField txt_kembalian;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_pembayaran;
    private javax.swing.JTextField txt_totalbayar;
    // End of variables declaration//GEN-END:variables

    private void setModel(DefaultComboBoxModel<String> pilihFilm) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
